In [1]:
import requests
from bs4 import BeautifulSoup

import pandas as pd
import os
import warnings
warnings.filterwarnings("ignore")

from tqdm import tqdm

In [6]:
# dapatkan url berita
def getUrlFromPage(url, headers, keyword):
    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")

        titles = soup.find_all("h3", class_="media__title")

        data = [
            {
                "title": a.get_text(strip=True),
                "link": a["href"],
                "keyword": keyword
            }
            for a in soup.select("h3.media__title a.media__link")
        ]

        return data

    except Exception as e:
        print(f"Error on page {url}: {e}")
        return None

def main(keyword="tbc"):
    try:
        headers = {
            "User-Agent": "Mozilla/5.0"
        }

        next_page = True
        page = 1
        all_url = []

        # ubah
        limit_page = 200
        start_page_url = f"https://www.detik.com/search/searchall?query={keyword}&result_type=relevansi&page="
        output_path = "data"
        filename = f"list_url_{keyword}.csv"

        while next_page:
            current_page_url = start_page_url+str(page)
            response = requests.get(current_page_url, headers=headers)

            print(f"page={page}, url='{current_page_url}', {response}")

            url = getUrlFromPage(current_page_url, headers, keyword)

            all_url.extend(url)

            if page == limit_page:
                next_page = False

            page += 1

        os.makedirs(output_path, exist_ok=True)

        df = pd.DataFrame(all_url)
        df.to_csv(f"{output_path}/{filename}", index=False)

    except Exception as e:
        print(f"Error: {e}")
        return None

main("tbc")
main("diabetes")

page=1, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=1', <Response [200]>
page=2, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=2', <Response [200]>
page=3, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=3', <Response [200]>
page=4, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=4', <Response [200]>
page=5, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=5', <Response [200]>
page=6, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=6', <Response [200]>
page=7, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=7', <Response [200]>
page=8, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=8', <Response [200]>
page=9, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=9', <Response [200]>
page=10, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=10', <Response [200]>
page=11, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=11', <Response [200]>
page=12, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=12', <Response [200]>
page=13, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=13', <Response [200]>
page=14, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=14', <Response [200]>
page=15, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=15', <Response [200]>
page=16, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=16', <Response [200]>
page=17, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=17', <Response [200]>
page=18, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=18', <Response [200]>
page=19, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=19', <Response [200]>
page=20, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=20', <Response [200]>
page=21, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=21', <Response [200]>
page=22, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=22', <Response [200]>
page=23, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=23', <Response [200]>
page=24, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=24', <Response [200]>
page=25, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=25', <Response [200]>
page=26, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=26', <Response [200]>
page=27, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=27', <Response [200]>
page=28, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=28', <Response [200]>
page=29, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=29', <Response [200]>
page=30, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=30', <Response [200]>
page=31, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=31', <Response [200]>
page=32, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=32', <Response [200]>
page=33, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=33', <Response [200]>
page=34, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=34', <Response [200]>
page=35, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=35', <Response [200]>
page=36, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=36', <Response [200]>
page=37, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=37', <Response [200]>
page=38, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=38', <Response [200]>
page=39, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=39', <Response [200]>
page=40, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=40', <Response [200]>
page=41, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=41', <Response [200]>
page=42, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=42', <Response [200]>
page=43, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=43', <Response [200]>
page=44, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=44', <Response [200]>
page=45, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=45', <Response [200]>
page=46, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=46', <Response [200]>
page=47, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=47', <Response [200]>
page=48, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=48', <Response [200]>
page=49, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=49', <Response [200]>
page=50, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=50', <Response [200]>
page=51, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=51', <Response [200]>
page=52, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=52', <Response [200]>
page=53, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=53', <Response [200]>
page=54, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=54', <Response [200]>
page=55, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=55', <Response [200]>
page=56, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=56', <Response [200]>
page=57, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=57', <Response [200]>
page=58, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=58', <Response [200]>
page=59, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=59', <Response [200]>
page=60, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=60', <Response [200]>
page=61, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=61', <Response [200]>
page=62, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=62', <Response [200]>
page=63, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=63', <Response [200]>
page=64, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=64', <Response [200]>
page=65, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=65', <Response [200]>
page=66, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=66', <Response [200]>
page=67, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=67', <Response [200]>
page=68, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=68', <Response [200]>
page=69, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=69', <Response [200]>
page=70, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=70', <Response [200]>
page=71, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=71', <Response [200]>
page=72, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=72', <Response [200]>
page=73, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=73', <Response [200]>
page=74, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=74', <Response [200]>
page=75, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=75', <Response [200]>
page=76, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=76', <Response [200]>
page=77, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=77', <Response [200]>
page=78, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=78', <Response [200]>
page=79, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=79', <Response [200]>
page=80, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=80', <Response [200]>
page=81, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=81', <Response [200]>
page=82, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=82', <Response [200]>
page=83, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=83', <Response [200]>
page=84, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=84', <Response [200]>
page=85, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=85', <Response [200]>
page=86, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=86', <Response [200]>
page=87, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=87', <Response [200]>
page=88, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=88', <Response [200]>
page=89, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=89', <Response [200]>
page=90, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=90', <Response [200]>
page=91, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=91', <Response [200]>
page=92, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=92', <Response [200]>
page=93, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=93', <Response [200]>
page=94, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=94', <Response [200]>
page=95, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=95', <Response [200]>
page=96, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=96', <Response [200]>
page=97, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=97', <Response [200]>
page=98, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=98', <Response [200]>
page=99, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=99', <Response [200]>
page=100, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=100', <Response [200]>
page=101, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=101', <Response [200]>
page=102, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=102', <Response [200]>
page=103, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=103', <Response [200]>
page=104, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=104', <Response [200]>
page=105, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=105', <Response [200]>
page=106, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=106', <Response [200]>
page=107, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=107', <Response [200]>
page=108, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=108', <Response [200]>
page=109, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=109', <Response [200]>
page=110, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=110', <Response [200]>
page=111, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=111', <Response [200]>
page=112, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=112', <Response [200]>
page=113, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=113', <Response [200]>
page=114, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=114', <Response [200]>
page=115, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=115', <Response [200]>
page=116, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=116', <Response [200]>
page=117, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=117', <Response [200]>
page=118, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=118', <Response [200]>
page=119, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=119', <Response [200]>
page=120, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=120', <Response [200]>
page=121, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=121', <Response [200]>
page=122, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=122', <Response [200]>
page=123, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=123', <Response [200]>
page=124, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=124', <Response [200]>
page=125, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=125', <Response [200]>
page=126, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=126', <Response [200]>
page=127, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=127', <Response [200]>
page=128, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=128', <Response [200]>
page=129, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=129', <Response [200]>
page=130, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=130', <Response [200]>
page=131, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=131', <Response [200]>
page=132, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=132', <Response [200]>
page=133, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=133', <Response [200]>
page=134, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=134', <Response [200]>
page=135, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=135', <Response [200]>
page=136, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=136', <Response [200]>
page=137, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=137', <Response [200]>
page=138, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=138', <Response [200]>
page=139, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=139', <Response [200]>
page=140, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=140', <Response [200]>
page=141, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=141', <Response [200]>
page=142, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=142', <Response [200]>
page=143, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=143', <Response [200]>
page=144, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=144', <Response [200]>
page=145, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=145', <Response [200]>
page=146, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=146', <Response [200]>
page=147, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=147', <Response [200]>
page=148, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=148', <Response [200]>
page=149, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=149', <Response [200]>
page=150, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=150', <Response [200]>
page=151, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=151', <Response [200]>
page=152, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=152', <Response [200]>
page=153, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=153', <Response [200]>
page=154, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=154', <Response [200]>
page=155, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=155', <Response [200]>
page=156, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=156', <Response [200]>
page=157, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=157', <Response [200]>
page=158, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=158', <Response [200]>
page=159, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=159', <Response [200]>
page=160, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=160', <Response [200]>
page=161, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=161', <Response [200]>
page=162, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=162', <Response [200]>
page=163, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=163', <Response [200]>
page=164, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=164', <Response [200]>
page=165, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=165', <Response [200]>
page=166, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=166', <Response [200]>
page=167, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=167', <Response [200]>
page=168, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=168', <Response [200]>
page=169, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=169', <Response [200]>
page=170, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=170', <Response [200]>
page=171, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=171', <Response [200]>
page=172, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=172', <Response [200]>
page=173, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=173', <Response [200]>
page=174, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=174', <Response [200]>
page=175, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=175', <Response [200]>
page=176, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=176', <Response [200]>
page=177, url='https://www.detik.com/search/searchall?query=tbc&result_type=relevansi&page=177', <Response [200]>

In [7]:
# merge
df_diabetes = pd.read_csv("data/list_url_diabetes.csv")
df_tbc = pd.read_csv("data/list_url_tbc.csv")

df = pd.concat([df_diabetes, df_tbc], ignore_index=True)
df.to_csv("data/list_url.csv")

In [8]:
# seleksi non artikel
df = pd.read_csv("data/list_url.csv")

def is_article(url):
    return ("berita" in url
            and "detiktv" not in url
            and "video" not in url
            and "20.detik.com" not in url)

df = df[df["link"].apply(is_article)]
df.to_csv("data/list_url_selected.csv")

In [9]:
# df.rename(columns={'label': 'keyword'}, inplace=True)
df

,Unnamed: 0,title,link,keyword
0,0,Andre Rosiade Bantu Istri Pemulung Pengidap Di...,https://news.detik.com/berita/d-8452634/andre-...,diabetes
1,1,Pasien Diabetes Tak Lagi Perlu Minum Obat Seum...,https://health.detik.com/berita-detikhealth/d-...,diabetes
8,8,18 April Hari Diabetes Nasional dan Kenali Car...,https://www.detik.com/bali/berita/d-8450035/18...,diabetes
14,14,Terungkap Pemicu Terbesar Gagal Ginjal Makin M...,https://health.detik.com/berita-detikhealth/d-...,diabetes
23,23,Jebakan 'Hidden Sugar' di Minuman Manis yang B...,https://health.detik.com/berita-detikhealth/d-...,diabetes
...,...,...,...,...
3830,3830,Pemkot Tangerang Raih 48 Penghargaan Sepanjang...,https://news.detik.com/berita/d-6478020/pemkot...,tbc
3831,3831,Kata Dokter Paru soal 619 Anak di Bantul Kena ...,https://health.detik.com/berita-detikhealth/d-...,tbc
3832,3832,1.332 Warga Tulungagung Positif TBC,https://www.detik.com/jatim/berita/d-6477178/1...,tbc
3836,3836,Jepang yang Bakal Wajibkan WNI Tes TBC Mulai 2...,https://health.detik.com/berita-detikhealth/d-...,tbc
3837,3837,"Alam Bintaro Tewas di Rumah Diduga karena TBC,...",https://www.detik.com/sumbagsel/berita/d-71219...,tbc

In [10]:
df = pd.read_csv("data/list_url_selected.csv")
df = df.rename(columns={'label': 'keyword'})

In [11]:
headers = {"User-Agent": "Mozilla/5.0"}

def get_content(url):
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            return None

        soup = BeautifulSoup(response.text, "html.parser")

        container = soup.select_one("div.detail__body-text.itp_bodycontent")

        if not container:
            container = soup.select_one("div.detail__body-text")

        if not container:
            container = soup.select_one("div.itp_bodycontent")

        if not container:
            print("Failed selector:", url)
            return None

        paragraphs = container.find_all("p")

        texts = []
        for p in paragraphs:
            txt = p.get_text(strip=True)

            if not txt:
                continue
            if "ADVERTISEMENT" in txt.upper():
                continue

            texts.append(txt)

        return " ".join(texts) if texts else None

    except:
        return None

tqdm.pandas()

content_series = df["link"].progress_apply(get_content)

100%|██████████| 2519/2519 [39:39<00:00,  1.06it/s]

In [12]:
df['content'] = content_series

In [13]:
df

,Unnamed: 0.1,Unnamed: 0,title,link,keyword,content
0,0,0,Andre Rosiade Bantu Istri Pemulung Pengidap Di...,https://news.detik.com/berita/d-8452634/andre-...,diabetes,Wakil Ketua Komisi VI DPR RI dari Fraksi Gerin...
1,1,1,Pasien Diabetes Tak Lagi Perlu Minum Obat Seum...,https://health.detik.com/berita-detikhealth/d-...,diabetes,Ketua Umum Perkumpulan Endokrinologi Indonesia...
2,8,8,18 April Hari Diabetes Nasional dan Kenali Car...,https://www.detik.com/bali/berita/d-8450035/18...,diabetes,"Setiap tahun, tanggal 18 April selalu dipering..."
3,14,14,Terungkap Pemicu Terbesar Gagal Ginjal Makin M...,https://health.detik.com/berita-detikhealth/d-...,diabetes,Kementerian Kesehatan RI mengungkap tren mengk...
4,23,23,Jebakan 'Hidden Sugar' di Minuman Manis yang B...,https://health.detik.com/berita-detikhealth/d-...,diabetes,Kabar baik bagi kesehatan publik di Indonesia....
...,...,...,...,...,...,...
2514,3830,3830,Pemkot Tangerang Raih 48 Penghargaan Sepanjang...,https://news.detik.com/berita/d-6478020/pemkot...,tbc,"Sepanjang tahun 2022, Pemerintah Kota (Pemkot)..."
2515,3831,3831,Kata Dokter Paru soal 619 Anak di Bantul Kena ...,https://health.detik.com/berita-detikhealth/d-...,tbc,Dinas Kesehatan Kabupaten Bantul melaporkan ad...
2516,3832,3832,1.332 Warga Tulungagung Positif TBC,https://www.detik.com/jatim/berita/d-6477178/1...,tbc,Dinas Kesehatan Tulungagung menemukan 12.384 w...
2517,3836,3836,Jepang yang Bakal Wajibkan WNI Tes TBC Mulai 2...,https://health.detik.com/berita-detikhealth/d-...,tbc,Kementerian Kesehatan RI (Kemenkes) menanggapi...
2518,3837,3837,"Alam Bintaro Tewas di Rumah Diduga karena TBC,...",https://www.detik.com/sumbagsel/berita/d-71219...,tbc,"Misteri kematian pria di Lubuklinggau, Sumater..."

In [14]:
df.isnull().sum()

Unnamed: 0.1     0
Unnamed: 0       0
title            0
link             0
keyword          0
content         22
dtype: int64

In [15]:
df.to_csv('data/dataset.csv')